name: Render Video
on:
  workflow_dispatch
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: bun i
      - run: pip install g4f
      - run: echo ${{ secrets.TAFAKOR_ID }}
      - run: touch .env &&
          echo TAFAKOR_ID=${{ secrets.TAFAKOR_ID }} >> .env &&
          echo USER_ID=${{ secrets.USER_ID }} >> .env &&
          echo USER_ACCESS_TOKEN=${{ secrets.USER_ACCESS_TOKEN }} >> .env &&
          echo PEXELS_KEY=${{ secrets.PEXELS_KEY }} >> .env
      - run: cat .env
      - run: bun render.ts
