name: Test / Render Video
on:
  workflow_dispatch:
    inputs:
      surah:
        description: "Surah Number"
        required: true
        default: "1"
      from:
        description: "Ayat From"
        required: true
        default: "4"
      to:
        description: "Ayat To"
        required: true
        default: "4"
      video:
        description: "Video"
        required: true
        default: "https://player.vimeo.com/progressive_redirect/playback/224857514/rendition/720p/file.mp4?loc=external&oauth2_token_id=1027659527&signature=a756b9db87ab75c38c60274686cd4b145a956cc878863f36fc8d03ca3dfc04d4#t=0"
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Emit input props
        run: echo $WORKFLOW_INPUT | tee input-props.json | jq -C '.'
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}

      - name: Bun Dependencies Install
        run: bun i
      - name: Install FFMPEG
        run: sudo apt install ffmpeg
      - name: Fetching latest chrome version
        run: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - name: Installing Chrome
        run: sudo dpkg -i google-chrome-stable_current_amd64.deb
      - name: Rendering Video
        run: bun ./pipe/test.ts
